### ISSUE TITLE
Traccar Service is destroyed automatically

### ISSUE THREAD

**Issue by simplywing** [tananaev/traccar-client-ios#61] opened 2017-09-26 12:22 UTC
Since version 5.x, Traccar Client is not fully working anymore. The service starts and everything seems to be fine, but aprox. 5min after locking the device, the service is destroyed and does not send data anymore. I tested this on 2 different iPhones (iPhone 6, iPhone SE), one with IOS 10 and the other with IOS 11, the issue is the same.

![image](https://user-images.githubusercontent.com/29959710/30859900-b27898f4-a2c5-11e7-93bf-f294fc8e2bcc.png)
My Settings for Traccar Client

**Comment by tananaev** [comment] 2017-09-26 20:22
Duplicate of #58.

**Closed by tananaev** 2017-09-26 20:22 UTC
